version: "3.8" # https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    volumes:
      - snipeit_public:/var/www/snipeit/public
      - ./config/snipeit_nginx.conf:/etc/nginx/templates/nginx.conf.template
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - ./config/yourdomain.test.crt:/etc/nginx/certs/yourdomain.test.crt
      # - ./config/yourdomain.test.key:/etc/nginx/certs/yourdomain.test.key
    networks:
      - web
    ports:
      # CHANGE TO "80:80" IF USING NGINX FOR SSL TERMINATION
      - "9080:80"
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - "443:443"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      # https://nginx.org/en/docs/ngx_core_module.html#worker_processes
      - NGINX_WORKER_PROCESSES=auto
      # https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile
      - NGINX_WORKER_RLIMIT_NOFILE=65535
      # https://nginx.org/en/docs/ngx_core_module.html#worker_connections
      - NGINX_WORKER_CONNECTIONS=65535
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      - NGINX_CLIENT_MAX_BODY_SIZE=0
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
      - NGINX_CLIENT_BODY_TIMEOUT=6666s
      - NGINX_HOST=snipeit.yourdomain.test
      # UNCOMMENT IF USING NGINX FOR SSL
      # - NGINX_SSL_CERT=yourdomain.test.crt
      # - NGINX_SSL_KEY=yourdomain.test.key

  snipeit:
    image: zeigren/snipe-it:latest # ghcr.io/zeigren/snipe-it-docker:latest
    # https://hub.docker.com/r/zeigren/snipe-it
    volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
      - snipeit:/var/www/snipeit/storage
      - snipeit_public:/var/www/snipeit/public
    networks: # https://docs.docker.com/compose/compose-file/compose-file-v3/#networks
      - web
      - db
      - redis
    environment: # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
      - DB_PASSWORD=CHANGEME
      - APP_URL=http://localhost:9080
      - COOKIE_DOMAIN=localhost
      # CHANGE TO true IF USING HTTPS
      - SECURE_COOKIES=false
      # Run first without APP_KEY to have the container create one
      # - APP_KEY=CHANGEME
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    # https://hub.docker.com/_/mariadb
    volumes:
      - snipeit_db:/var/lib/mysql
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_PASSWORD=CHANGEME
      - MYSQL_USER=snipeit
      - MYSQL_DATABASE=snipeit

  redis:
    image: redis:alpine
    # https://hub.docker.com/_/redis
    networks:
      - redis

volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
  snipeit:
  snipeit_db:
  snipeit_public:
  caddy_data:

networks: # https://docs.docker.com/compose/compose-file/compose-file-v3/#network-configuration-reference
  web:
  db:
  redis:
